=== 22mfdez/HI_LENGUAJEMARCAS/hito individual lenguaje de marcas/fase1.dtd
<!ELEMENT pedidos (a単o+)>
<!ELEMENT a単o (trimestre+)>
<!ATTLIST a単o a単o CDATA #REQUIRED>
<!ELEMENT trimestre (pedido+)>
<!ATTLIST trimestre trimestre CDATA #REQUIRED>
<!ELEMENT pedido (nombre, apellidos, telefono, direccion, correo, fecha_inclusion, detalle_pedido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion (calle, ciudad, codigo_postal, provincia)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT fecha_inclusion (#PCDATA)>
<!ELEMENT detalle_pedido (numero_pedido, fecha_compra, fecha_entrega, total_factura, producto+)>
<!ELEMENT numero_pedido (#PCDATA)>
<!ELEMENT fecha_compra (#PCDATA)>
<!ELEMENT fecha_entrega (#PCDATA)>
<!ELEMENT total_factura (#PCDATA)>
<!ELEMENT producto (nombre, referencia, precio, unidades)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>

=== 22mfdez/HI_LENGUAJEMARCAS/hito individual lenguaje de marcas/fase1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos SYSTEM "fase1.dtd">
<pedidos>
    <año año="2021">
        <trimestre trimestre="1">
        <pedido>
            <nombre>María</nombre>
            <apellidos>González Pérez</apellidos>
            <telefono>653-458-798</telefono>
            <direccion>
                <calle>Calle del Sol 123</calle>
                <ciudad>Madrid</ciudad>
                <codigo_postal>28001</codigo_postal>
                <provincia>Madrid</provincia>
            </direccion>
            <correo>maria.gonzalez@gmail.com</correo>
            <fecha_inclusion>2021-01-15</fecha_inclusion>
            <detalle_pedido>
                <numero_pedido>0001</numero_pedido>
                <fecha_compra>2021-01-15</fecha_compra>
                <fecha_entrega>2021-01-18</fecha_entrega>
                <total_factura>80.50</total_factura>
            <producto>
                <nombre>Camiseta de algodón size S</nombre>
                <referencia>1234</referencia>
                <precio>20.00</precio>
                <unidades>2</unidades>
            </producto>
            <producto>
                <nombre>Pantalón vaquero size S</nombre>
                <referencia>5678</referencia>
                <precio>35.95</precio>
                <unidades>1</unidades>
            </producto>
            <producto>
                <nombre>Jersey de lana size S</nombre>
                <referencia>9012</referencia>
                <precio>20.50</precio>
                <unidades>1</unidades>
            </producto>
            </detalle_pedido>
        </pedido>
        <pedido>
            <nombre>Javier</nombre>
            <apellidos>Rodríguez García</apellidos>
            <telefono>156-785-466</telefono>
            <direccion>
                <calle>Calle de la Luna 456</calle>
                <ciudad>Barcelona</ciudad>
                <codigo_postal>08001</codigo_postal>
                <provincia>Barcelona</provincia>
            </direccion>
            <correo>javier.rodriguez@gmail.com</correo>
            <fecha_inclusion>2021-02-01</fecha_inclusion>
            <detalle_pedido>
                <numero_pedido>0002</numero_pedido>
                <fecha_compra>2021-02-01</fecha_compra>
                <fecha_entrega>2021-02-04</fecha_entrega>
                <total_factura>51.90</total_factura>
            <producto>
                <nombre>Camisa de algodón roja size M</nombre>
                <referencia>5678</referencia>
                <precio>25.95</precio>
                <unidades>1</unidades>
            </producto>
            <producto>
                <nombre>Pantalón de cuero size M</nombre>
                <referencia>9012</referencia>
                <precio>25.95</precio>
                <unidades>1</unidades>
            </producto>
            </detalle_pedido>
        </pedido>
        <pedido>
            <nombre>Marta</nombre>
            <apellidos>Sanchez Torres</apellidos>
            <telefono>653-458-985</telefono>
            <direccion>
                <calle>Calle de los Planetas 45</calle>
                <ciudad>Jaén</ciudad>
                <codigo_postal>47852</codigo_postal>
                <provincia>Baeza</provincia>
            </direccion>
            <correo>martasnchz@gmail.com</correo>
            <fecha_inclusion>2021-02-22</fecha_inclusion>
            <detalle_pedido>
                <numero_pedido>0003</numero_pedido>
                <fecha_compra>2021-02-22</fecha_compra>
                <fecha_entrega>2021-02-29</fecha_entrega>
                <total_factura>69.95</total_factura>
            <producto>
                <nombre>Plumífero con capucha size L</nombre>
                <referencia>5014</referencia>
                <precio>69.95</precio>
                <unidades>1</unidades>
            </producto>
            </detalle_pedido>
        </pedido>
        <pedido>
            <nombre>Luis</nombre>
            <apellidos>García Pérez</apellidos>
            <telefono>458-789-123</telefono>
            <direccion>
                <calle>Calle del Canal 8</calle>
                <ciudad>Gandía</ciudad>
                <codigo_postal>69877</codigo_postal>
                <provincia>Valencia</provincia>
            </direccion>
            <correo>luisgp.12@gmail.com</correo>
            <fecha_inclusion>2021-02-23</fecha_inclusion>
            <detalle_pedido>
                <numero_pedido>0004</numero_pedido>
                <fecha_compra>2021-02-23</fecha_compra>
                <fecha_entrega>2021-02-30</fecha_entrega>
                <total_factura>19.99</total_factura>
            <producto>
                <nombre>Pack camisetas básicas size M</nombre>
                <referencia>01248</referencia>
                <precio>19.99</precio>
                <unidades>1</unidades>
            </producto>
            </detalle_pedido>
        </pedido>
        <pedido>
            <nombre>Rebeca</nombre>
            <apellidos>Fernández Torrijos</apellidos>
            <telefono>653-297-985</telefono>
            <direccion>
                <calle>Calle de la Fantasía 22</calle>
                <ciudad>Pinto</ciudad>
                <codigo_postal>28795</codigo_postal>
                <provincia>Madrid</provincia>
            </direccion>
            <correo>mrebecaf@gmail.com</correo>
            <fecha_inclusion>2021-02-23</fecha_inclusion>
            <detalle_pedido>
                <numero_pedido>0005</numero_pedido>
                <fecha_compra>2021-02-23</fecha_compra>
                <fecha_entrega>2021-02-26</fecha_entrega>
                <total_factura>38.94</total_factura>
            <producto>
                <nombre>Sudadera Oversized size S</nombre>
                <referencia>2145</referencia>
                <precio>25.95</precio>
                <unidades>1</unidades>
            </producto>
            <producto>
                <nombre>Leggins sintéticos size XS</nombre>
                <referencia>1498</referencia>
                <precio>12.99</precio>
                <unidades>1</unidades>
            </producto>
            </detalle_pedido>
        </pedido>
        <pedido>
            <nombre>Luis</nombre>
            <apellidos>García Pérez</apellidos>
            <telefono>458-789-123</telefono>
            <direccion>
                <calle>Calle del Canal 8</calle>
                <ciudad>Gandía</ciudad>
                <codigo_postal>69877</codigo_postal>
                <provincia>Valencia</provincia>
            </direccion>
            <correo>luisgp.12@gmail.com</correo>
            <fecha_inclusion>2021-02-24</fecha_inclusion>
            <detalle_pedido>
                <numero_pedido>0006</numero_pedido>
                <fecha_compra>2021-02-25</fecha_compra>
                <fecha_entrega>2021-02-27</fecha_entrega>
                <total_factura>46.90</total_factura>
            <producto>
                <nombre>Jean Regular Fit size M</nombre>
                <referencia>6584</referencia>
                <precio>30.95</precio>
                <unidades>1</unidades>
            </producto>
            <producto>
                <nombre>Sudadera Basic Beige size M</nombre>
                <referencia>1479</referencia>
                <precio>15.95</precio>
                <unidades>1</unidades>
            </producto>
            </detalle_pedido>
        </pedido>
        <pedido>
            <nombre>Luis</nombre>
            <apellidos>García Pérez</apellidos>
            <telefono>458-789-123</telefono>
            <direccion>
                <calle>Calle del Canal 8</calle>
                <ciudad>Gandía</ciudad>
                <codigo_postal>69877</codigo_postal>
                <provincia>Valencia</provincia>
            </direccion>
            <correo>luisgp.12@gmail.com</correo>
            <fecha_inclusion>2021-02-26</fecha_inclusion>
            <detalle_pedido>
                <numero_pedido>0007</numero_pedido>
                <fecha_compra>2021-03-01</fecha_compra>
                <fecha_entrega>2021-03-05</fecha_entrega>
                <total_factura>66.90</total_factura>
            <producto>
                <nombre>Joggers de algodón size M</nombre>
                <referencia>0458</referencia>
                <precio>20.95</precio>
                <unidades>1</unidades>
            </producto>
            <producto>
                <nombre>Chaqueta Cuero size M</nombre>
                <referencia>0698</referencia>
                <precio>45.95</precio>
                <unidades>1</unidades>
            </producto>
            </detalle_pedido>
        </pedido>
        <pedido>
            <nombre>Luis</nombre>
            <apellidos>García Pérez</apellidos>
            <telefono>458-789-123</telefono>
            <direccion>
                <calle>Calle del Canal 8</calle>
                <ciudad>Gandía</ciudad>
                <codigo_postal>69877</codigo_postal>
                <provincia>Valencia</provincia>
            </direccion>
            <correo>luisgp.12@gmail.com</correo>
            <fecha_inclusion>2021-03-01</fecha_inclusion>
            <detalle_pedido>
                <numero_pedido>0008</numero_pedido>
                <fecha_compra>2021-03-03</fecha_compra>
                <fecha_entrega>2021-03-06</fecha_entrega>
                <total_factura>19.99</total_factura>
            <producto>
                <nombre>Camiseta estampado Print size M</nombre>
                <referencia>2895</referencia>
                <precio>19.99</precio>
                <unidades>1</unidades>
            </producto>
            </detalle_pedido>
        </pedido>
        <pedido>
            <nombre>Luis</nombre>
